version: '3.1'

services:
#Each service represents a seperate container -> in this case php
#They are tab deliminated and require the tabs
  php:
    #image: php:7.4-apache
    build:
      context: . #local file dir to the file.
      dockerfile: Dockerfile
    ports:
      - 80:80 #left side our port, right side the containers port
    volumes:
      - ./src:/var/www/html/ #src files will be in the ./src -> local to my dir but mapped to the /var/www/.. dir

  db: #just means database
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080