name: Php Docker
on: push
jobs:
  build-container:
    name: Build container
    runs-on: windows-latest
    steps:
    - name: Checkout code from github
      uses: actions/checkout@v3
    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}