name: Php Docker
on: push
jobs:
  build-container:
    name: Build container
    runs-on: windows-latest
    steps:
    - name: Checkout code from github
      uses: actions/checkout@v3
    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      name: Build and push to Docker hub
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true, 
        tags: sketch1900/phpdocker:latest, sketch1900/phpdocker:${{ github.run_number }} #form of versioning